# -*- coding: utf-8 -*-
"""att_list_by_TS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/107N7BPUsGOpy7fISbvcFplhLE3-Fyxvd
"""

import pandas as pd

def make_att_list_by_TS(sorted_total_clustering_box = '', TS_list = '', path = ''):
  score_box = {}
  score = 15
  att_index = []

  df = pd.read_csv(path)

  end = len(df.cluster.unique())

  for item in sorted_total_clustering_box:
    score_box[item[0]] = score
    score -= 1

  score = 15
  for item in TS_list:
    score_box[item] = score
    score -= 1

  for i in range(end):
    att_index.append(list(df[df.cluster == str(i)].index))

  final_att_list = []

  for i in range(end):
    for index in att_index[sorted_total_clustering_box[:][i][0]]:
      final_att_list.append(df.Name[index])

  return final_att_list