# -*- coding: utf-8 -*-
"""경로를 계산할 여행지 선정.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11piYkGvMQQ4cCw1UyvKfv8G7_XvJDC8p
"""

import numpy as np
import pandas as pd

def choose_attraction(input = '', path = ''):
  df = pd.read_csv(path)
  end = len(df.cluster.unique())
  att_index = []

  for i in range(end):
    att_index.append(list(df[df.cluster == str(i)].index))

  cluster_num = []
  for i in range(len(df)):
    if df.cluster[i] != 'Nan':
      cluster_num.append(int(df.cluster[i]))

  df_clustering_box = {}
  for i in range(end):
    df_clustering_box[i] = cluster_num.count(i)

  indexbox = []
  clusterbox = []

  for name in input:
    ind = df[df.Name == name].index[0]
    indexbox.append(ind)
    clusterbox.append(df.cluster[ind])
  clusterbox = [int(num) for num in clusterbox]

  rec_clustering_box = {}
  for i in range(end):
    rec_clustering_box[i] = clusterbox.count(i)

  total_clustering_box = {}
  for i in range(end):
    total_clustering_box[i] = rec_clustering_box[i] / (df_clustering_box[i] + 1)

  sorted_total_clustering_box = sorted(total_clustering_box.items(), key=lambda item: item[1], reverse=True)

  final_att_list = []

  for i in range(end):
    for index in att_index[sorted_total_clustering_box[:][i][0]]:
      final_att_list.append(df.Name[index])

  return final_att_list