# -*- coding: utf-8 -*-
"""유저 정보가 담긴 csv 만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jEHbrVL1QRjBCpID_Jj-k8PphW2aa7Zw
"""

import pandas as pd

def make_csv_file(osaka_info_path = '', user_id = '', dir = ''):
    df = pd.read_csv(osaka_info_path)

    user_df = pd.DataFrame(df.Name)

    user_df['visit'] = 0
    user_df['candidate'] = 0
    user_df['clicked'] = 0
    user_df['suggested'] = 0

    user_df.to_csv(dir + user_id + '.csv', index=False)


